### ISSUE TITLE
Opening datepicker-dropdown popover sometimes shifts its anchor

### ISSUE THREAD

**Issue by p-himik** [Day8/re-com#119]
When you have an anchor very close to the bottom of the browser window, opening the popover will insert its tag before the anchor which will result in shifted anchor.
Same behavior in the latest Google Chrome and Firefox.
Bottom right of the image - the popover with removed z-index.
![dropdown-problem](https://cloud.githubusercontent.com/assets/4410314/19903762/5b76cccc-a0a2-11e6-9998-5e12be946f0c.png)

**Comment by Gregg8** [comment]
A new feature was added to the popover component so that if it detects there is not enough room in it's current position, it adjusts the position so it can be seen. There is a problem with popovers that have `:no-clip?` set (`datepicker-dropdown` sets this to true). They are adjusted but not perfectly. I have posted issue #113 and this should be addressed when that is completed.

**Comment by Gregg8** [comment]
Although I placed 2 `datepicker-dropdown` components on top of each other using the current re-com version, I couldn't get the results above.

However, #113 has now been fixed so you should try the latest to see if it sorts your issue.

**Comment by Gregg8** [comment]
OK, `1.1.0` had a flaw which affects this issue.

Now fixed in `1.2.0`. Make sure to test using this new version.
