### ISSUE TITLE
tag-dropdown: model does not support plain set, must be atom

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#234]
Demo example for tag-dropdown suggests a non atom can be passed for the `model`, but this causes a deref exception.

![image](https://user-images.githubusercontent.com/4626024/105947165-5ae0e500-60b4-11eb-8d0e-579fb2884079.png)

![image](https://user-images.githubusercontent.com/4626024/105947119-47357e80-60b4-11eb-914b-7d0071a6629e.png)

**Comment by superstructor** [comment]
Documentation is deployed on every push to `master`.

The last released version, `2.12.0`, did not support a non atom.

`master` does support a non-atom since  a8a45d84faba5cca4273137d1012c4d28647c6bd via `deref-or-value`.

Tested successfully on `master` today. This will work in any subsequent release.
