### ISSUE TITLE
allowing styling of outer rc-h-box

### ISSUE THREAD

**Issue by gberenfield** [Day8/re-com#29]
For things like datepickers, input-text boxes, checkboxes etc. that have an outer div-wrapper of class "rc-h-box", it would be nice to be able to tweak styling at that level as well.

I'm specifically trying to get a checkbox with a label to vertically align with other components in an h-box and due to the rc-h-box div, this doesn't seem possible.

**Comment by Gregg8** [comment]
The purpose of that wrapping div probably doesn't seem clear on first glance, but it is there because of the way flex box alignment works. The very short answer is that without it, those components would often "stretch" to fill their parent container. Looks very messy and is difficult to track down, especially when you're starting out.

I am trying to visualise your specific case here. Pasting the code fragment here would make that a lot easier if possible?

**Comment by gberenfield** [comment]
Sure.

The [checkbox] in `etable` is what I'd like to vertically center align (vertically aligned to the 'top')
```
(defn etable []
  (let [start-filter (subscribe [:end-filter])
        end-filter (subscribe [:start-filter])
        table-filter? (subscribe [:filter?])]
    [:div
     [:h2 "Expenses"]
     [h-box
      :justify :end
      :gap "6px"
      :children [[datepicker-dropdown :model start-filter :on-change #(dispatch [:filter-table-update % :start-filter]) :show-today? true]
                 [datepicker-dropdown :model end-filter :on-change #(dispatch [:filter-table-update % :end-filter]) :show-today? true]
                 [checkbox :model table-filter? :on-change #(dispatch [:filter-table-update % :filter?]) :label "filter?"]
                 [button :label "Print"]]]
     [expense-data-table]]))
```

**Comment by Gregg8** [comment]
You can achieve what you want by adding `:align :center` to the parent [h-box]

**Comment by gberenfield** [comment]
Thank you! Closing
