### ISSUE TITLE
Check-box styling is overridden by browser instead of bootstrap

### ISSUE THREAD

**Issue by hipitihop** [day8/re-com#306]
Check-box styling is overridden by browser instead of bootstrap:

Chrome:
![image](https://user-images.githubusercontent.com/4626024/133949843-e98f8843-2b61-4382-803c-cb3455e5ff6a.png)

FireFox:
![image](https://user-images.githubusercontent.com/4626024/133949850-de8d2d61-677a-4cad-a003-293af4ff558c.png)

Notice it not only affects the primary color, but also the disabled look.
Although we now support :parts this should probably use bootstrap defaults?

**Comment by MawiraIke** [comment]
After some checking, it seems like Bootstrap `v3`(which `re-com` uses) and Bootstrap `v4`  have no default colour for checkboxes. The default colour seems to have been added in Bootstrap `v5`. Adding support for this would mean hardcoding the styling. I would prefer this to wait for [component restyling](https://github.com/day8/re-com/issues/284) to be completed first since it will override the styling.

**Comment by hipitihop** [comment]
@MawiraIke I agree. closing
