### ISSUE TITLE
Better alert-boxes

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-com#32]
I'm finding the styling on the bootstrap "alerts" very brash and chocolate box.   The following is a quickly mocked alternative (which could easily be improved with more pixel wrangling) 

![better-alerts](https://cloud.githubusercontent.com/assets/3033376/8133035/ffcea42c-1168-11e5-9657-f3902d33ad0f.png)

So, the point is:  how to allow for variation?  Currently you must supply an `:alert-type` and that drives the CSS.  I'd like to be able to not use bootstrap and add a class to drive the L&F. 

---- 

Notes about the picture above: 
   - border-left-width:  4px
   - border-left-colour:   <as necessary>
   - no coloured text  (standard grey)
   - no rounded corners

:danger
border-left-colour:  rgba(255, 0, 0, 0.60)
background-color:  rgba(255, 32, 32, 0.05)

:warning
border-left-color:  orange
<no background>

:info
border-left-color:    green
background-color:    rgba(223, 240, 200, 0.40)

**Comment by Frozenlock** [comment]
The candy feel from bootstrap is probably caused by the border-radius. Not using any radius, like in your example, makes everything a little more 'serious'.
(Web devs went through all kinds of tricks to make rounded corners... and when it's finally easily available, people go back to basic shapes. :laughing: )

I think there should be a border on all sides. It is an alert after all; it should jump out to the user.

I wouldn't mind a little shadow either. I know all the current rage is flat and all that, but I like to think that some little things like this one can draw the user's attention when needed.

![image](https://cloud.githubusercontent.com/assets/1152041/8150197/12e4085e-12ae-11e5-9c82-45c2f0ce35e9.png)

My 2 cents.

**Comment by mike-thompson-day8** [comment]
We have a composite component, which is made up of parts like:
  - an outer box
  - a title 
  - a body section

These parts pretty much map one to one with  `[:div ]`

In such cases, we should have 3 named args for the `:style` for those three parts and perhaps also 3 `:class` equivalents as well.   Then we have given the component user  the maximum flexibility.

**Comment by Gregg8** [comment]
Implemented in [da865e2](https://github.com/Day8/re-com/commit/da865e28babc1481c279a0e4cbe4848b974ae967)
