### ISSUE TITLE
show version number on the demo page

### ISSUE THREAD

**Issue by aleksandersumowski** [Day8/re-com#48]
I've tried to use a 0.6.0 feature in 0.5.4 based on the example on the demo page. It would be useful to explicitly show the version used on the demo page or even better show when particular features were introduced. In this particular case it was the id-fn in the selection list.

**Comment by Gregg8** [comment]
It would not be sufficient to place a single version number on each demo page. In fact, the demo page will always be using the latest `re-com` so the number would be identical for each page...not that helpful.

The proper way would be to tag every argument with the version number when it was introduced and I think it would be quite messy and verbose to add version numbers all over the place so I am not in favour of doing that. 

In your example, I believe you would have seen a red message in in the console stating that `:id-fn` was an invalid argument, so at least you got something sensible there.

The real solution is to be on the latest version. Perhaps in this case, you didn't upgrade because this release is a SNAPSHOT? This is not something we intend doing on a regular basis.

**Comment by Gregg8** [comment]
Closing this. Feel free to re-open to continue discussions.
