### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by brandonparsons** [Day8/re-com#64]
Hi there!

I know you mention drag & drop in your TODO section. Is this in the works? Would it be very hard to implement? I'm trying to determine if I can use `re-com` for an upcoming project and drag & drop is a key feature.

:smile:

**Comment by mike-thompson-day8** [comment]
We've certainly done drag and drop interfaces, and they work :-)

Most  issues you run into will be around using the HTML5 DnD API  (which is a pig).  

The other issue that puzzled us for a while were reagent-related ones  ... we attached `drag-end` type event handlers to elements and then we'd remove those elements (because stuff was happening in response to the drag), and then wonder why we weren't getting drag-end events.   Given the HTML DnD API is so distractingly bad to deal with,  this issue took us a while to figure out.  

So, I guess I'm saying that there are no issues for re-com around drag-drop.  Your challenges will be elsewhere.   :-)

**Comment by brandonparsons** [comment]
Thanks for the input! 

Trying to sort out our requirements now - I'm hoping to be able to use this :+1:
